name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true

      - name: Restore dependencies (locked)
        run: dotnet restore GitHubActionsDotNet.sln 

      - name: Run tests
        run: dotnet test GitHubActionsDotNet.sln --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dometrain-artifact
          path: artifacts/

  deploy_dev:
    name: Deploy Dev  
    needs: build
    uses: ./.github/workflows/step-deploy.yml 
    with:
      env: dev
    secrets: inherit


  deploy_prod:
    name: Deploy Prod
    needs: deploy_dev
    uses: ./.github/workflows/step-deploy.yml 
    with:
      env: prod
    secrets: inherit 
