name: CI

on:
  push:
    branches: 
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: 'nuget'

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Run tests
        run: dotnet test --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dometrain-artifact
          path: artifacts/

  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dometrain-artifact
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-dometrain-github-actions-erisjakupi-dev
          package: artifacts

          
