name: Secrets workflow

on:
  pull_request:
    branches: ["main"]

env: 
  API_CSPROJ_PATH: "./src/GithubActionsDotnet.Api/GithubActionsDotnet.Api.csproj"

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest
    env: 
      JOB_NAME: "secrets"
    steps:
      - name: Echo environment variable
        run: curl -h API_KEY

  new_job:
    name: Secrets Demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "new_job"
    steps:
      - name: Echo environment variable
        run: echo "The value of $JOB_NAME is $API_CSPROJ_PATH"
