name: "Step - Deploy"

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  # First job to check environment and provide clear messaging
  check_environment:
    name: Check Environment
    runs-on: ubuntu-latest
    steps:
      - name: Check if environment is production
        if: inputs.env == 'prod'
        run: |
          echo "::error::Production deployments are not supported. Please use 'dev' environment only."
          exit 1
          
  # Only runs if the environment is not 'prod'
  deploy:
    name: Deploy ${{ inputs.env }}
    needs: check_environment
    runs-on: ubuntu-latest
    if: inputs.env != 'prod'
    environment: ${{ inputs.env }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dometrain-artifact
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-dometrain-github-actions-erisjakupi-${{ inputs.env }}
          package: artifacts/
                        

